[project]
name = "MIB-circuit-track"
version = "0.1.0"
description = "A set of scripts for finding and evaluating component circuits."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "eap",
    "tabulate>=0.9.0",
]

[tool.uv.sources]
eap = { path = "EAP-IG" }
